# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# Used for making pop up windows 
'''
from MaskFeedWindow import Ui_MaskFeedWindow
from GeometryEditingWindow import Ui_GeometryEditingWindow
from ProjectorConfigurationWindow import Ui_ProjectorConfigurationWindow
'''
class Ui_MainWindow(object):

    # Used for making pop up windows 
    '''
    def gotoMaskFeedWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MaskFeedWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def gotoGeometryEditingWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_GeometryEditingWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def gotoProjectorConfigurationWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ProjectorConfigurationWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    '''

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainmenu_widget = QtWidgets.QWidget(self.centralwidget)
        self.mainmenu_widget.setGeometry(QtCore.QRect(70, 30, 681, 471))
        self.mainmenu_widget.setStyleSheet("background-color: rgb(106, 106, 106);")
        self.mainmenu_widget.setObjectName("mainmenu_widget")
        self.PC_bt = QtWidgets.QPushButton(self.mainmenu_widget, clicked = lambda: self.gotoProjectorConfigurationWindow())
        self.PC_bt.setGeometry(QtCore.QRect(90, 320, 151, 41))
        self.PC_bt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(68, 68, 68);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 68, 68, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(68, 68, 68, 200);\n"
"}")
        self.PC_bt.setObjectName("PC_bt")
        self.MF_bt = QtWidgets.QPushButton(self.mainmenu_widget, clicked = lambda: self.gotoMaskFeedWindow())
        self.MF_bt.setGeometry(QtCore.QRect(270, 320, 151, 41))
        self.MF_bt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(68, 68, 68);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 68, 68, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(68, 68, 68, 200);\n"
"}")
        self.MF_bt.setObjectName("MF_bt")
        self.GE_bt = QtWidgets.QPushButton(self.mainmenu_widget, clicked = lambda: self.gotoGeometryEditingWindow())
        self.GE_bt.setGeometry(QtCore.QRect(460, 320, 151, 41))
        self.GE_bt.setStyleSheet("QPushButton {\n"
"    background-color: rgb(68, 68, 68);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(68, 68, 68, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(68, 68, 68, 200);\n"
"}")
        self.GE_bt.setObjectName("GE_bt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.Projector_Configuration_menu = QtWidgets.QMenu(self.menubar)
        self.Projector_Configuration_menu.setObjectName("Projector_Configuration_menu")
        self.Mask_Feed_menu = QtWidgets.QMenu(self.menubar)
        self.Mask_Feed_menu.setObjectName("Mask_Feed_menu")
        self.Geometry_Editing_menu = QtWidgets.QMenu(self.menubar)
        self.Geometry_Editing_menu.setObjectName("Geometry_Editing_menu")
        self.User_Manual_menu = QtWidgets.QMenu(self.menubar)
        self.User_Manual_menu.setObjectName("User_Manual_menu")
        MainWindow.setMenuBar(self.menubar)
        self.Add_Projector_action = QtWidgets.QAction(MainWindow)
        self.Add_Projector_action.setObjectName("Add_Projector_action")
        self.Remove_Projector_action = QtWidgets.QAction(MainWindow)
        self.Remove_Projector_action.setObjectName("Remove_Projector_action")
        self.Projector_Configuration_menu.addAction(self.Add_Projector_action)
        self.Projector_Configuration_menu.addAction(self.Remove_Projector_action)
        self.menubar.addAction(self.Projector_Configuration_menu.menuAction())
        self.menubar.addAction(self.Mask_Feed_menu.menuAction())
        self.menubar.addAction(self.Geometry_Editing_menu.menuAction())
        self.menubar.addAction(self.User_Manual_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PC_bt.setText(_translate("MainWindow", "Projector Configuration"))
        self.MF_bt.setText(_translate("MainWindow", "Mask Feed"))
        self.GE_bt.setText(_translate("MainWindow", "Geometry Editing"))
        self.Projector_Configuration_menu.setTitle(_translate("MainWindow", "Projector Configuration"))
        self.Mask_Feed_menu.setTitle(_translate("MainWindow", "Mask Feed"))
        self.Geometry_Editing_menu.setTitle(_translate("MainWindow", "Geometry Editing"))
        self.User_Manual_menu.setTitle(_translate("MainWindow", "User Manual"))
        self.Add_Projector_action.setText(_translate("MainWindow", "Add Projector"))
        self.Remove_Projector_action.setText(_translate("MainWindow", "Remove Projector"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
